name: MkDocs Build and Deploy

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2.4.0
      - name: Setup Cache
        uses: actions/cache@v2.1.7
        with:
          key: ${{ github.ref }}
          path: site
      - name: Deploy MkDocs
        uses: vinomaster/mkdocs-ghpages-docker-action@v1
